[package]
name = "ultranet-crypto"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
rust-version.workspace = true
repository.workspace = true
description = "Ultranet cryptographic primitives. Thin wrapper around ed25519-dalek."

[lints]
workspace = true

[dependencies]
ed25519-dalek = { version = "2", features = ["rand_core"] }
rand_core = { version = "0.6", features = ["getrandom"] }
